### ISSUE TITLE
Incorrect sensor detection on two test cameras

### ISSUE THREAD

**Issue by widgetii** [OpenIPC/ipctool#14]
```
172.17.32.51# ./ipc_chip_info 
Chip: HiSilicon 3516cv300
Sensor: Sony IMX323

172.17.32.52# ./ipc_chip_info 
Chip: HiSilicon 3516cv300
Sensor: Sony IMX323
```
`cat /proc/umap/sys` on both shows `ar0237` type but `Sofia` detects as `SC2235`:

```
[DEBUG]: mirror=0
[DEBUG]: Flip=0
[DEBUG]: ~~~~~~~~~~SC2235_init  JJ ~~~~~~~~~
[DEBUG]: Denoise level:  Day[3]      Night[3]
[DEBUG]: Denoise level:  Day[3]      Night[3]
[DEBUG]: IR: 65
```

**Comment by widgetii** [comment]
Checked once again (this time both cameras are on OpenIPC firmware) and it's confirmed that the real sensor name is `IMX323`:

```
sensors:
- vendor: Sony
  model: IMX323
  control:
    bus: 0
    type: i2c
    addr: 0x34
  data:
    type: DC
  clock: 27MHz
  ```
