### ISSUE TITLE
Please add the output for more information about the Ethernet interface

### ISSUE THREAD

**Issue by ZigFisher** [OpenIPC/ipctool#17]
This code allows us to get excellent information about the processors of the first group

```
for hieth in $(ls -l /sys/module/hieth/parameters | awk '{print $9}'); do echo ${hieth}=$(cat /sys/module/hieth/parameters/${hieth}); done
```
`mdioifd=1
mdioifu=1
phyaddrd=1
phyaddru=0
`

Please add the information in some other order, see the example.

```
---
chip:
  vendor: HiSilicon
  model: 3518EV100
ethernet:
  mac: "00:00:23:34:45:66"
  mdioifu: 1
  mdioifd: 1
  phyaddru: 1
  phyaddrd: 0
......
```

Note:  mdioifX  0=mii, 1=rmii

TNX !

P.S. It would be very good to find the same data for other processor groups, but I haven't been able to do it yet..
