### ISSUE TITLE
Upgrade / Restore fails on Videopark devices

### ISSUE THREAD

**Issue by DSchndr** [OpenIPC/ipctool#37]
Hi, I've tested upgrade / restore functunality of the tool and it fails on my devices
I have some devices to test and can flash ofw back, how should I debug the flash process?

Also, should i upload a dump somewhere? I did not see the hunter streamer binary anywhere

```
/tmp # ./ipctool
---
chip:
  vendor: HiSilicon
  model: 3516CV300
ethernet:
  mac: "e0:61:b2:4e:a6:ff"
  u-mdio-phyaddr: 1
  phy-id: 0x001cc816
  d-mdio-phyaddr: 0
rom:
  - type: nor
    block: 64K
    partitions:
      - name: boot
        size: 0x40000
        sha1: 48195e9b
        contains:
          - name: uboot-env
            offset: 0x20000
      - name: defcfg
        size: 0x10000
        sha1: 67d9fc96
      - name: kernel
        size: 0x1f0000
        sha1: 7625fbaa
      - name: root
        size: 0x960000
        path: /,squashfs
        sha1: cb44f590
      - name: custom
        size: 0x400000
        sha1: f427120a
      - name: config
        size: 0x60000
        sha1: 928813b9
    size: 16M
    addr-mode: 3-byte
ram:
  total: 256M
  media: 144M
firmware:
  kernel: "3.18.20 (Wed Apr 4 14:46:18 CST 2018)"
  toolchain: gcc version 4.9.4 20150629 (prerelease) (Hisilicon_v500_20150831)
  libc: uClibc 0.9.33.2
  sdk: "Hi3516CV300_MPP_V1.0.1.0 B070 Release (Feb 13 2017, 20:42:49)"
  main-app: hunter
sensors:
- vendor: Sony
  model: IMX323
  control:
    bus: 0
    type: i2c
    addr: 0x34
  data:
    type: DC
  clock: 37.125MHz

```
```
~ # cat /proc/partitions
major minor  #blocks  name

  31        0        256 mtdblock0
  31        1         64 mtdblock1
  31        2       1984 mtdblock2
  31        3       9600 mtdblock3
  31        4       4096 mtdblock4
  31        5        384 mtdblock5
~ # cat /proc/mounts
rootfs / rootfs rw 0 0
/dev/root / squashfs ro,relatime 0 0
devtmpfs /dev devtmpfs rw,relatime,size=53760k,nr_inodes=13440,mode=755 0 0
proc /proc proc rw,relatime 0 0
sysfs /sys sysfs rw,relatime 0 0
tmpfs /tmp tmpfs rw,relatime 0 0
tmpfs /var tmpfs rw,relatime 0 0
devpts /dev/pts devpts rw,relatime,mode=600 0 0
/dev/mtdblock4 /mnt/special squashfs ro,relatime 0 0
/dev/mtdblock5 /mnt/mtd jffs2 rw,sync,relatime 0 0

```
```
~ # dmesg | grep hisi_spi_nor.0
hisi-sfc hisi_spi_nor.0: all blocks is unlocked.
hisi-sfc hisi_spi_nor.0: gd25q128 (16384 Kbytes)

```
```
/tmp # ./ipctool upgrade upgrade.cv300
There was no Sofia process detected
Use --force switch to skip the check
aborting...
/tmp # ./ipctool upgrade upgrade.cv300 --force
There was no Sofia process detected
Unmounting /mnt/special
Unmounting /mnt/mtd
Using 'upgrade.cv300' as upgrade bundle
        boot    0xb68d4010, size: 262144 bytes
        env     0x63010, size: 65536 bytes
        kernel  0xb66f3010, size: 1966080 bytes
        rootfs  0xb6272010, size: 4718592 bytes
Analyzing boot
Analyzing env
Analyzing kernel
Analyzing rootfs
Upgrading boot
Flashing [wwww]
Upgrading env
Flashing [w]
Upgrading kernel
Flashing [wwwwwwwwwwwwwwwwwwwwwwwwwwwwww]
Upgrading rootfs
Could not open mtd device: 46.....................................................]

Something went wrong, aborting...
Early exit, check the logs

```
```
/tmp # ./ipctool restore bak
Restoring the backup

Loading backup from file bak...
Are you sure to proceed? (y/n)? y
Checking boot...
[0] 0x00000000  0x00040000      48195e9b        48195e9b
Checking defcfg...
[1] 0x00040000  0x00010000      67d9fc96        67d9fc96
Checking kernel...
[2] 0x00050000  0x001f0000      7625fbaa        7625fbaa
Checking root...
[3] 0x00240000  0x00960000      cb44f590        cb44f590
Checking custom...
[4] 0x00ba0000  0x00400000      f427120a        f427120a
Not checked (no SHA1)
[5] 0x00fa0000  0x00060000           n/a
Backups were checked
Analyzing boot
Analyzing defcfg
Analyzing kernel
Analyzing root
Analyzing custom
Analyzing config
Restoring boot
Flashing [wwww]
Restoring defcfg
Flashing [w]
Restoring kernel
Fail to erase +0x40000...................]

Something went wrong, aborting...
```
