### ISSUE TITLE
Not support this sensor

### ISSUE THREAD

**Issue by vinibali** [OpenIPC/ipctool#53]

**Comment by dimerr** [comment]
so which sensor you actually have there?

**Comment by vinibali** [comment]
I don't really know. It's a 5MP one.
* the panel with IR leds looks like this (FY-S63): [https://www.tradechina.com/FY-S63-3-smd-led-ir-Array-pcb-board-CCTV-Accessories_192493008.html](https://www.tradechina.com/FY-S63-3-smd-led-ir-Array-pcb-board-CCTV-Accessories_192493008.html)
* the camera itself have the following numbers: cmos0253p-38x38-wp1 and f20201222v

**Comment by vinibali** [comment]
I think I found it:
* 0235p-5333p: (5.0M Black light illumination H.265 AI IP Camera Module)[https://www.xiongmaitech.com/en/index.php/product/product-detail/185/187/377]

**Comment by vinibali** [comment]
https://github.com/OpenIPC/firmware/issues/64

**Comment by vinibali** [comment]
Is there any way, how I can help to get his supported?

**Comment by widgetii** [comment]
You should make changes in source code, test on your hardware and make a PR

**Comment by vinibali** [comment]
Can you please help meg and make a bit more detailed guide?

**Comment by widgetii** [comment]
Do you have C programming skills?

**Comment by vinibali** [comment]
sort of

**Comment by widgetii** [comment]
Then do debug ipctool binary on your hardware figuring out why sensor is not responding to i2c commands

**Comment by vinibali** [comment]
it seems, i've attached the cable to the sensor wrongly :)
```
root@openipc-xm530:/tmp# ipctool 
---
chip:
  vendor: Xiongmai
  model: XM550
board:
  vendor: Xiongmai
ethernet:
  mac: "xx:xx:xx:xx:xx:xx"
rom:
  - type: nor
    block: 64K
    partitions:
      - name: boot
        size: 0x40000
        sha1: 9d2158df
        contains:
          - name: xmcrypto
            offset: 0x2fc00
          - name: uboot-env
            offset: 0x30000
      - name: env
        size: 0x10000
        sha1: b0152796
      - name: kernel
        size: 0x200000
        sha1: 86f4024b
      - name: rootfs
        size: 0x500000
        path: /,squashfs
        sha1: 55c76271
      - name: rootfs_data
        size: 0xb0000
        path: /overlay,jffs2,rw
    size: 8M
ram:
  total: 128M
  media: 93M
firmware:
  kernel: "3.10.103+ (SMP Sat Feb 11 23:00:38 UTC 2023)"
  toolchain: gcc version 8.4.0 (Buildroot -gff5aa3b6-dirty) 
  main-app: /usr/bin/majestic
sensors:
- vendor: SmartSens
  model: SC5332
  control:
    bus: 0
    type: i2c
    addr: 0x60
```
